ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS "dataNascimento" TIMESTAMP(3);
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS "cidade" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS "estado" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS "endereco" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS "bio" TEXT NOT NULL DEFAULT '';
