ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS "statusEstudo" TEXT NOT NULL DEFAULT 'nao_estudou';
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS "planoTipo" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Aluno" ADD COLUMN IF NOT EXISTS "planoVencimento" TIMESTAMP(3);
